import { motion, useScroll, useMotionValueEvent } from 'motion/react';
import { useRef, useState } from 'react';

const steps = [
  {
    id: "scope",
    number: "01",
    title: "Scope",
    description: "Start your project. Use AI or work with an expert to build a custom scope to share with our engineers."
  },
  {
    id: "blueprint",
    number: "02",
    title: "Blueprint",
    description: "Get a comprehensive technical roadmap, timeline, and budget estimate instantly generated by AI."
  },
  {
    id: "dashboard",
    number: "03",
    title: "Dashboard",
    description: "Track progress, review assets, and collaborate with your dedicated team in real-time."
  }
];

export function HowItWorksV11() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [activeStepIndex, setActiveStepIndex] = useState(0);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });

  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    const index = Math.min(2, Math.floor(latest * 3));
    setActiveStepIndex(index);
  });

  return (
    <section className="bg-white py-24 relative border-b border-[#EFE9E4]">
      <div ref={containerRef} className="container mx-auto px-6 lg:px-16 relative min-h-[300vh] flex flex-col lg:flex-row gap-12 lg:gap-24">
        
        {/* Left Column: Sticky Text */}
        <div className="lg:w-2/5 lg:h-screen lg:sticky lg:top-0 flex flex-col justify-center py-24">
          <div className="mb-12 border-l-2 border-[#FCD34D] pl-6">
            <h4 className="text-[#B45309] font-bold uppercase tracking-widest text-[10px] mb-4">How It Works</h4>
            <h2 className="text-4xl lg:text-5xl font-serif text-[#1A1A1A] leading-tight mb-2">
              The smarter way to <br />
              build your startup
            </h2>
          </div>

          <div className="space-y-12 border-l border-[#D1C7BD] pl-6">
            {steps.map((step, i) => (
              <div 
                key={step.id}
                className={`transition-all duration-500 relative ${
                  activeStepIndex === i ? "opacity-100" : "opacity-30"
                }`}
              >
                {/* Active Step Indicator */}
                {activeStepIndex === i && (
                  <div className="absolute -left-[26px] top-0 w-3 h-3 bg-[#F59E0B] border-2 border-white" />
                )}
                
                <div className="flex items-baseline gap-4 mb-3">
                  <span className={`text-xs font-bold uppercase tracking-widest transition-colors duration-500 ${
                    activeStepIndex === i ? "text-[#B45309]" : "text-[#CCCCCC]"
                  }`}>
                    {step.number}
                  </span>
                  <h3 className={`text-2xl font-serif transition-colors duration-500 ${
                    activeStepIndex === i ? "text-[#1A1A1A]" : "text-[#CCCCCC]"
                  }`}>
                    {step.title}
                  </h3>
                </div>
                <p className={`text-base leading-relaxed font-serif transition-all duration-500 ${
                  activeStepIndex === i ? "text-[#666666] h-auto opacity-100" : "text-[#CCCCCC] h-0 opacity-0 overflow-hidden"
                }`} style={{ fontFamily: 'Lora, serif' }}>
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column: Sticky Visual - Editorial Layout */}
        <div className="lg:w-3/5 lg:h-screen lg:sticky lg:top-0 flex flex-col items-center justify-center">
           <div className="relative w-full max-w-2xl aspect-[4/3] border border-[#EFE9E4] bg-[#FAF8F6] p-12">
             
             {/* Step-Based Content */}
             <motion.div
               key={activeStepIndex}
               initial={{ opacity: 0 }}
               animate={{ opacity: 1 }}
               transition={{ duration: 0.4 }}
               className="w-full h-full flex flex-col justify-center"
             >
               {activeStepIndex === 0 && (
                 <div className="space-y-6">
                   <div className="border-l-2 border-[#F59E0B] pl-4">
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold mb-2">Project Type</div>
                     <div className="text-lg text-[#1A1A1A] font-medium">AI Platform Development</div>
                   </div>
                   <div className="border-l-2 border-[#F59E0B] pl-4">
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold mb-2">Timeline</div>
                     <div className="text-lg text-[#1A1A1A] font-medium">8-12 Weeks</div>
                   </div>
                   <div className="border-l-2 border-[#F59E0B] pl-4">
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold mb-2">Budget Range</div>
                     <div className="text-lg text-[#1A1A1A] font-medium">$30,000 - $50,000</div>
                   </div>
                 </div>
               )}

               {activeStepIndex === 1 && (
                 <div className="space-y-8">
                   <div className="border border-[#EFE9E4] bg-white p-6">
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold mb-3">Technical Roadmap</div>
                     <div className="space-y-2 text-sm text-[#444444]">
                       <div className="flex justify-between border-b border-[#EFE9E4] pb-2">
                         <span>Phase 1: Foundation</span>
                         <span className="font-bold">Week 1-2</span>
                       </div>
                       <div className="flex justify-between border-b border-[#EFE9E4] pb-2">
                         <span>Phase 2: Development</span>
                         <span className="font-bold">Week 3-8</span>
                       </div>
                       <div className="flex justify-between border-b border-[#EFE9E4] pb-2">
                         <span>Phase 3: Launch</span>
                         <span className="font-bold">Week 9-12</span>
                       </div>
                     </div>
                   </div>
                 </div>
               )}

               {activeStepIndex === 2 && (
                 <div className="grid grid-cols-2 gap-6">
                   <div className="border border-[#EFE9E4] bg-white p-6">
                     <div className="text-3xl font-serif text-[#1A1A1A] mb-2">85%</div>
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold">Progress</div>
                   </div>
                   <div className="border border-[#EFE9E4] bg-white p-6">
                     <div className="text-3xl font-serif text-[#1A1A1A] mb-2">12</div>
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold">Tasks Done</div>
                   </div>
                   <div className="border border-[#EFE9E4] bg-white p-6">
                     <div className="text-3xl font-serif text-[#1A1A1A] mb-2">3</div>
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold">Team Members</div>
                   </div>
                   <div className="border border-[#EFE9E4] bg-white p-6">
                     <div className="text-3xl font-serif text-[#1A1A1A] mb-2">24h</div>
                     <div className="text-xs uppercase tracking-widest text-[#888888] font-bold">Avg Response</div>
                   </div>
                 </div>
               )}
             </motion.div>

           </div>

           {/* Progress Indicators */}
           <div className="flex gap-3 mt-8">
             {[0, 1, 2].map((i) => (
               <div 
                 key={i}
                 className={`h-1 transition-all duration-300 ${
                   activeStepIndex === i 
                     ? "w-12 bg-[#F59E0B]" 
                     : "w-1 bg-[#D1C7BD]"
                 }`}
               />
             ))}
           </div>
        </div>

      </div>
    </section>
  );
}
