import { motion, useScroll, useMotionValueEvent, AnimatePresence } from 'motion/react';
import { useRef, useState } from 'react';
import { ScreenScopeContent, ScreenBudgetContent, ScreenBlueprintContent, ScreenDashboardContent, BrowserFrame } from './HowItWorksScreensV6';

const steps = [
  {
    id: "scope",
    title: "Scope",
    description: "Start your project. Use AI or work with an expert to build a custom scope to share with our engineers.",
    screens: [0, 1] // Maps to Scope & Budget screens
  },
  {
    id: "blueprint",
    title: "Blueprint",
    description: "Get a comprehensive technical roadmap, timeline, and budget estimate instantly generated by AI.",
    screens: [2] // Maps to Blueprint screen
  },
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Track progress, review assets, and collaborate with your dedicated team in real-time.",
    screens: [3] // Maps to Dashboard screen
  }
];

export function HowItWorksV6() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [activeScreenIndex, setActiveScreenIndex] = useState(0);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });

  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    // Map scroll progress to 4 screens (0, 1, 2, 3)
    const index = Math.min(3, Math.floor(latest * 4));
    setActiveScreenIndex(index);
  });

  // Calculate active text step
  const activeStepIndex = steps.findIndex(s => s.screens.includes(activeScreenIndex));

  return (
    <section className="bg-[#FAFAFA] py-24 relative">
      <div ref={containerRef} className="container mx-auto px-6 lg:px-12 relative min-h-[300vh] flex flex-col lg:flex-row gap-12 lg:gap-24">
        
        {/* Left Column: Sticky Text */}
        <div className="lg:w-1/3 lg:h-screen lg:sticky lg:top-0 flex flex-col justify-center py-24">
          <div className="mb-12">
            <h4 className="text-[#FF6A3D] font-bold uppercase tracking-widest text-sm mb-4">How It Works</h4>
            <h2 className="text-4xl lg:text-5xl font-semibold text-[#00334F] leading-tight mb-4 font-display">
              The smarter way to <br />
              build your startup
            </h2>
          </div>

          <div className="space-y-8">
            {steps.map((step, i) => (
              <div 
                key={step.id}
                className={`transition-all duration-500 ${
                  activeStepIndex === i ? "opacity-100" : "opacity-30 blur-[0.5px]"
                }`}
              >
                 <div className="flex items-baseline gap-4 mb-2">
                   <span className={`text-4xl font-bold font-display transition-colors duration-500 ${
                     activeStepIndex === i ? "text-[#00334F]" : "text-slate-300"
                   }`}>
                     {i + 1}.
                   </span>
                   <h3 className={`text-3xl font-bold font-display transition-colors duration-500 ${
                     activeStepIndex === i ? "text-[#00334F]" : "text-slate-300"
                   }`}>
                     {step.title}
                   </h3>
                 </div>
                 <p className={`text-lg leading-relaxed text-slate-500 pl-10 transition-all duration-500 ${
                   activeStepIndex === i ? "h-auto opacity-100" : "h-0 opacity-0 overflow-hidden"
                 }`}>
                   {step.description}
                 </p>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column: Sticky Screens */}
        <div className="lg:w-2/3 lg:h-screen lg:sticky lg:top-0 flex flex-col items-center justify-center">
           <div className="relative w-full max-w-xl aspect-[4/3]">
             
             {/* The Fixed Frame */}
             <BrowserFrame className="h-full bg-white transition-shadow duration-500 hover:shadow-[0_30px_60px_-12px_rgba(0,0,0,0.12)]">
               
               {/* Content Swapper */}
               <div className="absolute inset-0 w-full h-full">
                 <AnimatePresence initial={false}>
                   {activeScreenIndex === 0 && (
                     <ScreenWrapper key="scope">
                       <ScreenScopeContent isActive={activeScreenIndex === 0} />
                     </ScreenWrapper>
                   )}
                   {activeScreenIndex === 1 && (
                     <ScreenWrapper key="budget">
                       <ScreenBudgetContent isActive={activeScreenIndex === 1} />
                     </ScreenWrapper>
                   )}
                   {activeScreenIndex === 2 && (
                     <ScreenWrapper key="blueprint">
                       <ScreenBlueprintContent isActive={activeScreenIndex === 2} />
                     </ScreenWrapper>
                   )}
                   {activeScreenIndex === 3 && (
                     <ScreenWrapper key="dashboard">
                       <ScreenDashboardContent isActive={activeScreenIndex === 3} />
                     </ScreenWrapper>
                   )}
                 </AnimatePresence>
               </div>

             </BrowserFrame>

           </div>

           {/* Carousel Dots */}
           <div className="flex gap-2 mt-8">
             {[0, 1, 2, 3].map((i) => (
               <div 
                 key={i}
                 className={`h-2 rounded-full transition-all duration-300 ${
                   activeScreenIndex === i 
                     ? "w-8 bg-[#FF6A3D]" 
                     : "w-2 bg-slate-300"
                 }`}
               />
             ))}
           </div>
        </div>

      </div>
    </section>
  );
}

function ScreenWrapper({ children }: { children: React.ReactNode }) {
  return (
    <motion.div
      className="absolute inset-0 w-full h-full bg-white"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{
        duration: 0.4,
        ease: "easeInOut"
      }}
    >
      {children}
    </motion.div>
  );
}
